"""Writers for the IncidentReport.

Two outputs:
  - report.json   canonical, machine-readable artifact (versioned)
  - report.md     human-readable companion derived from the JSON

Both land in `.whychanged/` at the analyzed repo root.
"""

from __future__ import annotations

from pathlib import Path

from whychanged.models import IncidentReport

OUTPUT_DIR_NAME = ".whychanged"


def write_json(report: IncidentReport, root: Path) -> Path:
    out_dir = root / OUTPUT_DIR_NAME
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "report.json"
    out_path.write_text(
        report.model_dump_json(indent=2, exclude_none=False),
        encoding="utf-8",
    )
    return out_path


def write_markdown(report: IncidentReport, root: Path, max_rows: int = 25) -> Path:
    out_dir = root / OUTPUT_DIR_NAME
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "report.md"

    lines: list[str] = []
    lines.append("# What changed?")
    lines.append("")
    lines.append(
        f"> Generated by **whychanged v{report.tool_version}** at "
        f"{report.generated_at.isoformat(timespec='seconds')}"
    )
    lines.append(f"> Schema: `{report.schema_version}`")
    lines.append("")
    lines.append("---")
    lines.append("")

    w = report.window
    lines.append("## Window")
    lines.append("")
    if report.service:
        lines.append(f"- **Service:** `{report.service}`")
    if w.incident_at is not None:
        lines.append(f"- **Incident:** {w.incident_at.isoformat(timespec='seconds')}")
    lines.append(f"- **Since:** {w.since.isoformat(timespec='seconds')}")
    lines.append(f"- **Until:** {w.until.isoformat(timespec='seconds')}")
    lines.append("")

    if not report.ranked:
        lines.append("_No changes found in this window._")
        lines.append("")
        out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return out_path

    top = report.top_culprit
    if top is not None:
        lines.append("## Most likely culprit")
        lines.append("")
        lines.append(
            f"- **Score:** {top.score:.2f}  ·  "
            f"**Kind:** `{top.change.kind}`  ·  "
            f"**Source:** `{top.change.source}`"
        )
        lines.append(f"- **When:** {top.change.timestamp.isoformat(timespec='seconds')}")
        if top.change.actor:
            lines.append(f"- **Who:** {top.change.actor}")
        lines.append(f"- **What:** {top.change.summary}")
        if top.reasons:
            lines.append("- **Why this rank:** " + "; ".join(top.reasons))
        lines.append("")

    lines.append("## All changes (ranked)")
    lines.append("")
    lines.append("| Score | When | Kind | Actor | Summary |")
    lines.append("|---:|---|---|---|---|")
    for rc in report.ranked[:max_rows]:
        when = rc.change.timestamp.isoformat(timespec="seconds")
        actor = rc.change.actor or "-"
        summary = rc.change.summary.replace("|", "\\|")
        lines.append(f"| {rc.score:.2f} | {when} | `{rc.change.kind}` | {actor} | {summary} |")
    if len(report.ranked) > max_rows:
        lines.append(
            f"| _... and {len(report.ranked) - max_rows} more in report.json_ |  |  |  |  |"
        )

    lines.append("")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_path
