"""Writers for the CostReport.

Two outputs:
  - report.json   canonical, machine-readable artifact (versioned)
  - report.md     human-readable companion derived from the JSON

Both land in `.tokencost/` at the working directory root.

The Markdown is tuned for finance review: dollars with two decimals,
sortable by cost, breakdowns named the way a CFO would search for them.
"""

from __future__ import annotations

from pathlib import Path

from tokencost.models import MICROS_PER_USD, Bucket, CostReport

OUTPUT_DIR_NAME = ".tokencost"


def _fmt_usd(micros: int) -> str:
    """Render micro-USD as a $X.XX (or $X.XXXX for sub-cent) string."""
    usd = micros / MICROS_PER_USD
    if abs(usd) >= 0.01 or usd == 0:
        return f"${usd:,.2f}"
    return f"${usd:,.4f}"


def write_json(report: CostReport, root: Path) -> Path:
    out_dir = root / OUTPUT_DIR_NAME
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "report.json"
    out_path.write_text(
        report.model_dump_json(indent=2, exclude_none=False),
        encoding="utf-8",
    )
    return out_path


def _bucket_table(title: str, buckets: list[Bucket], max_rows: int) -> list[str]:
    if not buckets:
        return []
    lines: list[str] = [f"### {title}", ""]
    lines.append("| Label | Calls | Input tokens | Output tokens | Cost |")
    lines.append("|---|---:|---:|---:|---:|")
    for b in buckets[:max_rows]:
        lines.append(
            f"| `{b.label}` | {b.calls:,} | "
            f"{b.input_tokens:,} | {b.output_tokens:,} | "
            f"{_fmt_usd(b.cost_micros)} |"
        )
    if len(buckets) > max_rows:
        lines.append(f"| _... and {len(buckets) - max_rows} more in report.json_ |  |  |  |  |")
    lines.append("")
    return lines


def write_markdown(report: CostReport, root: Path, max_rows_per_breakdown: int = 25) -> Path:
    out_dir = root / OUTPUT_DIR_NAME
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "report.md"

    lines: list[str] = []
    lines.append("# LLM cost report")
    lines.append("")
    lines.append(
        f"> Generated by **tokencost v{report.tool_version}** at "
        f"{report.generated_at.isoformat(timespec='seconds')}"
    )
    lines.append(f"> Schema: `{report.schema_version}`")
    lines.append("")
    lines.append("---")
    lines.append("")

    lines.append("## Window")
    lines.append("")
    lines.append(f"- **Start:** {report.window_start.isoformat(timespec='seconds')}")
    lines.append(f"- **End:**   {report.window_end.isoformat(timespec='seconds')}")
    lines.append("")

    lines.append("## Totals")
    lines.append("")
    lines.append(f"- **Total cost:** {_fmt_usd(report.total_cost_micros)}")
    lines.append(f"- **Total calls:** {report.total_calls:,}")
    lines.append(f"- **Input tokens:**  {report.total_input_tokens:,}")
    lines.append(f"- **Output tokens:** {report.total_output_tokens:,}")
    lines.append("")

    if report.total_calls == 0:
        lines.append("_No usage in this report. Nothing to bill._")
        lines.append("")
        out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return out_path

    lines.append("## Breakdowns")
    lines.append("")
    lines.extend(_bucket_table("By feature", report.by_feature, max_rows_per_breakdown))
    lines.extend(_bucket_table("By model", report.by_model, max_rows_per_breakdown))
    lines.extend(_bucket_table("By environment", report.by_environment, max_rows_per_breakdown))
    lines.extend(_bucket_table("By actor", report.by_actor, max_rows_per_breakdown))

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_path
