"""Writers for the architecture artifact.

Two outputs:
  - architecture.json - canonical, machine-readable artifact (versioned)
  - architecture.md   - human-readable companion derived from the JSON

Both land in `.repox/` at the analyzed repo root.
"""

from __future__ import annotations

from pathlib import Path

from repox.models import Architecture, Dependency

OUTPUT_DIR_NAME = ".repox"


def _format_bytes(n: int) -> str:
    """Format a byte count as a human-friendly string (B / KB / MB / GB)."""
    size = float(n)
    for unit in ("B", "KB", "MB", "GB"):
        if size < 1024 or unit == "GB":
            if unit == "B":
                return f"{int(size)} B"
            return f"{size:.1f} {unit}"
        size /= 1024
    return f"{size:.1f} TB"


def write_json(arch: Architecture, root: Path) -> Path:
    """Write the canonical JSON artifact and return its path."""
    out_dir = root / OUTPUT_DIR_NAME
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "architecture.json"
    out_path.write_text(
        arch.model_dump_json(indent=2, exclude_none=False),
        encoding="utf-8",
    )
    return out_path


def _grouped_deps(deps: list[Dependency]) -> dict[str, list[Dependency]]:
    groups: dict[str, list[Dependency]] = {}
    for d in deps:
        groups.setdefault(d.kind, []).append(d)
    return groups


def write_markdown(arch: Architecture, root: Path) -> Path:
    """Write the human-readable Markdown companion and return its path."""
    out_dir = root / OUTPUT_DIR_NAME
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "architecture.md"

    lines: list[str] = []
    lines.append(f"# Architecture - {arch.repo.name}")
    lines.append("")
    lines.append(
        f"> Generated by **Repo X-ray v{arch.tool_version}** at "
        f"{arch.generated_at.isoformat(timespec='seconds')}"
    )
    lines.append(f"> Schema: `{arch.schema_version}`")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Overview
    lines.append("## Overview")
    lines.append("")
    lines.append(f"- **Root:** `{arch.repo.root}`")
    lines.append(f"- **Total files:** {arch.repo.total_files:,}")
    lines.append(f"- **Total size:** {_format_bytes(arch.repo.total_size_bytes)}")
    lines.append(f"- **Total lines:** {arch.repo.total_lines:,}")
    lines.append("")

    # Languages
    if arch.languages:
        lines.append("## Languages")
        lines.append("")
        lines.append("| Language | Files | Lines | Size |")
        lines.append("|---|---:|---:|---:|")
        for lang in arch.languages:
            lines.append(
                f"| {lang.name} | {lang.file_count:,} | "
                f"{lang.line_count:,} | {_format_bytes(lang.bytes)} |"
            )
        lines.append("")

    # Entry points
    if arch.entry_points:
        lines.append("## Entry points")
        lines.append("")
        for ep in arch.entry_points:
            extra = f" - _{ep.detail}_" if ep.detail else ""
            lines.append(f"- `{ep.path}` ({ep.kind}){extra}")
        lines.append("")
    else:
        lines.append("## Entry points")
        lines.append("")
        lines.append(
            "_None detected. Repo X-ray looked for declarations in known "
            "manifests (pyproject.toml, package.json, Cargo.toml, go.mod) "
            "and a small set of conventional file names (main.py, index.js, "
            "Dockerfile, etc.)._"
        )
        lines.append("")

    # Manifests + dependencies
    if arch.dependencies and (arch.dependencies.manifests or arch.dependencies.dependencies):
        lines.append("## Manifests")
        lines.append("")
        if arch.dependencies.manifests:
            lines.append("| Manifest | Package | Version | Declared deps |")
            lines.append("|---|---|---|---:|")
            for m in arch.dependencies.manifests:
                lines.append(
                    f"| `{m.kind}` ({m.path}) | "
                    f"{m.package_name or '-'} | "
                    f"{m.package_version or '-'} | "
                    f"{m.dependency_count} |"
                )
            lines.append("")

        groups = _grouped_deps(arch.dependencies.dependencies)
        if groups:
            for label, kind in (
                ("Runtime", "runtime"),
                ("Dev", "dev"),
                ("Optional", "optional"),
                ("Build", "build"),
            ):
                deps = groups.get(kind, [])
                if not deps:
                    continue
                lines.append(f"### {label} dependencies ({len(deps)})")
                lines.append("")
                shown = deps[:30]
                for d in shown:
                    spec = f" `{d.version_spec}`" if d.version_spec else ""
                    lines.append(f"- `{d.name}`{spec}  _(from {d.source})_")
                if len(deps) > 30:
                    lines.append(f"- _... and {len(deps) - 30} more in architecture.json._")
                lines.append("")

    # Conventions
    if arch.conventions is not None:
        c = arch.conventions
        lines.append("## Conventions")
        lines.append("")
        layout_bits: list[str] = []
        if c.has_src_layout:
            layout_bits.append("`src/<package>/` layout")
        if c.has_tests_dir:
            layout_bits.append("dedicated tests directory")
        if c.has_docs_dir:
            layout_bits.append("dedicated docs directory")
        layout = ", ".join(layout_bits) if layout_bits else "no obvious layout markers"

        indent_desc: str = c.primary_indent
        if c.primary_indent == "space" and c.indent_width:
            indent_desc = f"{c.indent_width}-space"
        elif c.primary_indent == "tab":
            indent_desc = "tabs"

        lines.append(f"- **Layout:** {layout}")
        lines.append(f"- **Indent:** {indent_desc}")
        lines.append(f"- **License:** {c.primary_license or 'not detected'}")
        if c.config_files:
            joined = ", ".join("`" + f + "`" for f in c.config_files)
            lines.append(f"- **Config files present:** {joined}")
        lines.append("")

    # Call graph (new in 0.2.0)
    if arch.call_graph is not None and (arch.call_graph.imports or arch.call_graph.symbols):
        lines.append("## Call graph")
        lines.append("")
        cg = arch.call_graph
        in_repo = [imp for imp in cg.imports if imp.target_file is not None]
        external = len(cg.imports) - len(in_repo)
        public_syms = [s for s in cg.symbols if s.is_public]
        lines.append(
            f"- **Imports:** {len(cg.imports):,} total "
            f"({len(in_repo):,} in-repo, {external:,} external)"
        )
        lines.append(f"- **Symbols:** {len(cg.symbols):,} total ({len(public_syms):,} public)")
        lines.append("")

        # Top 10 most-imported in-repo files (a useful "core modules" signal).
        if in_repo:
            from collections import Counter

            counts: Counter[str] = Counter(
                imp.target_file for imp in in_repo if imp.target_file is not None
            )
            top = counts.most_common(10)
            if top:
                lines.append("### Most imported (top 10)")
                lines.append("")
                lines.append("| Target | Imported by |")
                lines.append("|---|---:|")
                for path, n in top:
                    lines.append(f"| `{path}` | {n} |")
                lines.append("")

    # Roadmap reminder
    lines.append("## What's next for Repo X-ray")
    lines.append("")
    lines.append(
        "- v0.3: tree-sitter call graph (function call edges), JS / TS / Go / Rust support."
    )
    lines.append("- v0.4: incremental updates (`repox update`); MCP server.")
    lines.append("- v0.5: stable artifact format, GitHub Action, public release.")
    lines.append("")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_path
