"""Writers for the selection report.

Two outputs:
  - selection.json - canonical, machine-readable artifact (versioned)
  - selection.md   - human-readable companion derived from the JSON

Both land in `.sts/` at the analyzed repo root.
"""

from __future__ import annotations

from pathlib import Path

from sts.models import SelectionReport

OUTPUT_DIR_NAME = ".sts"


def write_json(report: SelectionReport, root: Path) -> Path:
    """Write the canonical JSON artifact and return its path."""
    out_dir = root / OUTPUT_DIR_NAME
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "selection.json"
    out_path.write_text(
        report.model_dump_json(indent=2, exclude_none=False),
        encoding="utf-8",
    )
    return out_path


def write_markdown(report: SelectionReport, root: Path) -> Path:
    """Write the human-readable Markdown companion and return its path."""
    out_dir = root / OUTPUT_DIR_NAME
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "selection.md"

    lines: list[str] = []
    lines.append("# Test selection")
    lines.append("")
    lines.append(
        f"> Generated by **sts v{report.tool_version}** at "
        f"{report.generated_at.isoformat(timespec='seconds')}"
    )
    lines.append(f"> Schema: `{report.schema_version}`")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Inputs
    lines.append("## Inputs")
    lines.append("")
    lines.append(f"- **Repo:** `{report.inputs.repo_root}`")
    lines.append(f"- **Diff source:** `{report.inputs.diff_source}`")
    lines.append(f"- **Changed files:** {len(report.inputs.changed_files)}")
    if report.inputs.changed_files:
        lines.append("")
        for cf in report.inputs.changed_files[:20]:
            lines.append(f"  - `{cf}`")
        if len(report.inputs.changed_files) > 20:
            lines.append(
                f"  - _... and {len(report.inputs.changed_files) - 20} more in selection.json._"
            )
    lines.append("")

    # Headline
    s = report.stats
    if report.fallback_run_all:
        lines.append(
            f"## Verdict: **run all {s.total_tests_in_repo} tests** (safe-default fallback)"
        )
        if report.fallback_reason:
            lines.append("")
            lines.append(f"_{report.fallback_reason}_")
    else:
        lines.append(
            f"## Verdict: **{s.must_run} must-run**, "
            f"**{s.should_run} should-run**, "
            f"**{s.can_skip} skip** (of {s.total_tests_in_repo} total)"
        )
    lines.append("")

    # Selections
    if report.selections:
        lines.append("## Selections")
        lines.append("")
        lines.append("| Priority | Path | Framework | Kind | Reason |")
        lines.append("|---|---|---|---|---|")
        for sel in report.selections:
            lines.append(
                f"| `{sel.priority}` | `{sel.test.path}` | "
                f"{sel.test.framework} | {sel.test.kind} | {sel.reason} |"
            )
        lines.append("")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_path
